import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Box } from "@mui/material";

export default function Home({ data }) {
  const allImages = data.map((obj) => obj.img_url);
  const [{ S }] = allImages;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box className="home-wrapper">
          {data.map((item, index) => (
            <Box key={index}>
              <img src={S} alt="" width={200} height={200} />
              <h3>{item.title.S}</h3>
              <Box>{item.artist.S}</Box>
            </Box>
          ))}
        </Box>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await fetch(
      "https://8s7zz37dt0.execute-api.us-east-1.amazonaws.com/dev/content"
    );
    const data = await res.json();
    return {
      props: { data },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {},
    };
  }
}
